name: Run Tests
on: [push, pull_request, create]
jobs:
  runTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Install dependencies
        run: sudo apt-get install -y libevent-dev python3-pip python3-virtualenv
      - name: Run Tests Tests
        run: |
          mvn package
          ./src/test/resources/run-s3-tests.sh
      - name: Build Docker Image
        run: ./publish_img.sh
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}